# You must change these to your own details.
[package]
name = "hora-wasm"
description = "javascript binding for hora"
version = "0.1.0"
authors = ["aljun <gagasalamer@outlook.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[features]
default = ["wee_alloc"]

[dependencies]
wasm-bindgen = "0.2.45"
cfg-if = "1.0.0"
wee_alloc = { version = "0.4.2", optional = true }
real_hora = { package = "hora", version = "0.1.0" }
getrandom = { version = "0.2.3", features=["js"]}
# wasm-bindgen-futures = "0.4.24"
# wasm-bindgen-rayon = "1.0"
# rayon = "1.5.1"

[dependencies.web-sys]
version = "0.3.22"
features = ["console"]

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.24"
futures = "0.3.15"
js-sys = "0.3.22"
