# You must change these to your own details.
[package]
name = "hora-wasm"
description = "javascript binding for hora"
version = "0.1.0"
authors = ["aljun <gagasalamer@outlook.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[features]
default = ["wee_alloc"]

[dependencies]
wasm-bindgen = "0.2.75"
cfg-if = "1.0.0"
wee_alloc = { version = "0.4.5", optional = true }
real_hora = { package = "hora", version = "0.1.0" }
getrandom = { version = "0.2.3", features=["js"]}
wasm-bindgen-futures = "0.4.25"
wasm-bindgen-rayon = "1.0.3"
rayon = "1.5.1"



[dev-dependencies]
wasm-bindgen-test = "0.3.25"
futures = "0.3.16"
js-sys = "0.3.52"
